### PR TITLE
https

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Comment by marioidival** [comment]
Hello @RekGRpth please, run `go fmt` in your code.

**Comment by RekGRpth** [comment]
Done

**Review by tiaguinho — APPROVED** [review]

**Review by felipeweb — CHANGES_REQUESTED** [review]
don't need else
 ```go
if config.PrestConf.HTTPSMode {
		l.Fatal(http.ListenAndServeTLS(addr, config.PrestConf.HTTPSCert, config.PrestConf.HTTPSKey, nil))
              return
	}
	l.Fatal(http.ListenAndServe(addr, nil))
```

**Review by crgimenes — APPROVED** [review]

**Comment by felipeweb** [comment]
@RekGRpth  we merge and we will make this small change

**Pull request merged**
